id: I928451B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T15:39:31+00:00'
last_modified: '2022-06-08T17:17:10.871992+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3724
  title: དཔལ་ལྡན་ཤངས་པ་བཀའ་བརྒྱུད་ཀྱི་འདོན་ཆ་ཉེར་མཁོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    76C3:
      image_group_id: I1KG3726
      title: ''
      total_pages: 538
      order: 1
      base_file: 76C3.txt
    B410:
      image_group_id: I1KG3727
      title: ''
      total_pages: 430
      order: 2
      base_file: B410.txt
    F0DC:
      image_group_id: I1KG3728
      title: ''
      total_pages: 636
      order: 3
      base_file: F0DC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
