id: P010754
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG3724
  title: དཔལ་ལྡན་ཤངས་པ་བཀའ་བརྒྱུད་ཀྱི་འདོན་ཆ་ཉེར་མཁོ།
  author: ''
  volumes:
    9799993d9df64f168dce93fedd82859d:
      image_group_id: I1KG3726
      title: ''
      volume_number: 1
      total_pages: 538
      base_file: v001.txt
    8d1d107ec8284c4a8e1c8c76ba5788d3:
      image_group_id: I1KG3727
      title: ''
      volume_number: 2
      total_pages: 430
      base_file: v002.txt
    1d90216df6e44297a431c09ee34d0da2:
      image_group_id: I1KG3728
      title: ''
      volume_number: 3
      total_pages: 636
      base_file: v003.txt
